USE ASSIGNMENT;
CREATE TABLE STUDENT
( 
STUDENT_ID VARCHAR (100) PRIMARY KEY,
FIRST_NAME VARCHAR (100),
LAST_NAME VARCHAR (100),
GPA DECIMAL (3,2),
ENROLLMENT_DATE DATETIME,
MAJOR TEXT
);

INSERT INTO STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,GPA,ENROLLMENT_DATE,MAJOR)
VALUE

(201,'Shivansh','Mahajon',8.79,'2021-09-01,09:30','Computer Science'),
(202,'Umesh','Sharma',8.44,'2021-09-01,08:30','Mathematics'),
(203,'Rakesh','Kumar',5.6,'2021-09-01,10:00','Biology'),
(204,'Radha','Sharma',9.2,'2021-09-01,12:45','Chemistry'),
(205,'Kush','Kumer',7.85,'2021-09-01,08:30','Physics'),
(206,'Prem','Chopra',9.56,'2021-09-01,02:30','History'),
(207,'Pankaj','Vats',9.78,'2021-09-01,02:30','English'),
(208,'Navleen','Kaur',7,'2021-09-01,06:30','Mathematics');

SELECT * FROM STUDENT; 


CREATE TABLE PROGRAM (
STUDENT_REF_ID VARCHAR (100),
PROGRAM_NAME VARCHAR (100),
PROGRAM_START_DATE DATETIME
);

CREATE TABLE SCHOLARSHIP (
STUDENT_REF_ID VARCHAR(100),
SCHOLARSHIP_AMOUNT DECIMAL,
SCHOLARSHIP_DATE DATETIME
);

INSERT INTO SCHOLARSHIP(STUDENT_REF_ID,SCHOLARSHIP_AMOUNT,SCHOLARSHIP_DATE)
VALUES

(201,'5000','2021-10-15,00:00:00'),
(202,'4500','2021-10-15,00:00:00'),
(203,'3000','2021-10-15,00:00:00'),
(204,'4000','2021-10-15,00:00:00');

SELECT upper(FIRST_NAME) as STUDENT_NAME From Student;

SELECT DISTINCT MAJOR from STUDENT;

SELECT INSTR(LOWER(FIRST_NAME),'a')FROM Student WHERE FIRST_NAME='Shivansh';  

SELECT DISTINCT MAJOR, LENGTH(MAJOR)FROM Student;

SELECT REPLACE(FIRST_NAME,'a','A') FROM Student;

SELECT CONCAT(FIRST_NAME,'',LAST_NAME)AS COMPLETE_NAME FROM Student;

SELECT *FROM Student ORDER BY FIRST_NAME,MAJOR DESC;

SELECT * FROM Student WHERE FIRST_NAME IN ('Prem','Shivansh');

SELECT * FROM Student WHERE FIRST_NAME NOT IN ('Prem','Shivansh');

SELECT * FROM Student WHERE FIRST_NAME LIKE'%a';

SELECT * FROM Student WHERE FIRST_NAME LIKE'_a';

SELECT * FROM Student WHERE GPA BETWEEN 9.00 AND 9.99;

SELECT Major,COUNT(*)as TOTAL_COUNT FROM Student WHERE MAJOR ='Computer Science';

SELECT
      Student.FIRST_NAME,
      Student.LAST_NAME,
      Scholarship.SCHOLARSHIP_AMOUNT,
      Scholarship.SCHOLARSHIP_DATE
FROM
      Student
INNER JOIN
       Scholarship ON Student.STUDENT_ID=Scholarship.STUDENT_REF_ID;
       
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME)AS FULL_NAME
FROM Student WHERE GPA BETWEEN 8.5 and 9.5;

SELECT MAJOR,COUNT(MAJOR) from Student group by MAJOR order by COUNT(MAJOR)DESC;

SELECT * FROM Student WHERE student_id%2!=0;

SELECT * FROM Student WHERE student_id%2=0;

SELECT Student.FIRST_NAME,Student.LAST_NAME,
Scholarship.SCHOLARSHIP_AMOUNT,
Scholarship.SCHOLARSHIP_DATE FROM Student LEFT JOIN
Scholarship ON Student.STUDENT_ID=
Scholarship.STUDENT_REF_ID;

SELECT * from Student ORDER BY GPA DESC LIMIT 5;

SELECT * from Student ORDER BY GPA DESC LIMIT 4,1;

SELECT * FROM Student s1
WHERE 4 =
   (SELECT COUNT(DISTINCT (s2.GPA))
   FROM Student s2
   WHERE s2.GPA>=s1.GPA
);

SELECT s1.*FROM Student s1,Student s2 WHERE s1.GPA=s2.GPA AND s1.Student_id != s2.Student_id;

SELECT MAX(GPA)FROM Student
WHERE GPA NOT IN(SELECT MAX(GPA)FROM Student);

SELECT *FROM Student
UNION ALL
SELECT *FROM Student ORDER BY STUDENT_ID;

SELECT STUDENT_ID FROM Student
WHERE STUDENT_ID NOT IN (SELECT STUDENT_REF_ID FROM Scholarship);


SELECT MAJOR,COUNT(MAJOR)AS MAJOR_COUNT FROM Student GROUP BY MAJOR HAVING COUNT(MAJOR)<4;

SELECT*
FROM(
	SELECT*
    FROM Student
    ORDER BY STUDENT_ID DESC
    LIMIT 5)
    AS subquery 
    ORDER BY STUDENT_ID;
    
    
SELECT DISTINCT GPA FROM Student S1
WHERE 3>= (SELECT COUNT(DISTINCT GPA) FROM Student S2 WHERE S1.GPA<=S2.GPA)
ORDER BY S1.GPA DESC;


SELECT DISTINCT GPA FROM Student S1
WHERE 3>= (SELECT COUNT(DISTINCT GPA) FROM Student S2 WHERE S1.GPA>=S2.GPA)
ORDER BY S1.GPA DESC;






SELECT MAJOR, MAX(GPA) as MAXGPA FROM Student GROUP BY MAJOR ;


CREATE TABLE CloneTable AS SELECT * FROM Student;






SELECT MAJOR,AVG(GPA) AS AVERAGE_GPA FROM Student GROUP BY MAJOR; 

SELECT * FROM Student ORDER BY GPA DESC LIMIT 3;

SELECT MAJOR,COUNT(STUDENT_ID) AS HIGH_GPA_COUNT
FROM Student
WHERE GPA>7.5
GROUP BY MAJOR;

SELECT * FROM Student WHERE GPA=(SELECT GPA FROM Student WHERE STUDENT_ID=201);

















